//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;Device sampleRate=&quot;10.0&quot; name=&quot;Mazak1&quot; iso841Class=&quot;1&quot; uuid=&quot;nist-opcda-net-2-mt-connect&quot; id=&quot;DDDD01&quot;&gt;
        ///      &lt;Description manufacturer=&quot;Mazak&quot; serialNumber=&quot;00001&quot;&gt;&lt;/Description&gt;
        ///      &lt;Components&gt;
        ///        &lt;Axes name=&quot;Axes&quot; id=&quot;DDDD02&quot;&gt;
        ///          &lt;DataItems&gt;
        ///            &lt;DataItem type=&quot;PATH_FEEDRATE&quot; name=&quot;path_feedratefrt&quot; category=&quot;SAMPLE&quot; id=&quot;DDDD03&quot; units=&quot;MILLIMETER/SECOND&quot; subType=&quot;ACTUAL&quot;/&gt;
        ///            &lt;DataItem category=&quot;SAMPLE&quot; id=&quot;DDDD04&quot; name=&quot;path_feedrateovr&quot; type=&quot;OTHER&quot; units=&quot;PERC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceTemplate {
            get {
                return ResourceManager.GetString("DeviceTemplate", resourceCulture);
            }
        }
    }
}
